### ISSUE TITLE
CI testing

### ISSUE THREAD

**Issue by DDoSolitary** [dokan-dev/dokan-rust#1]
@Liryna I've sent an request to allow my AppVeyor account to access this repo. I should be able to set up CI testing once you approve the request.

BTW, documentation is complete and now I'm migrating my "yasfw" project to use this library. This way, I can make sure that this library won't cause any surprises when used in real world applications. (Acutally I've found and fixed several such problems that the unit tests failed to catch when writing the documentation, so I'm not 100% sure now) I should be able to release it to crates.io after getting this done.

**Comment by Liryna** [comment]
Hi @DDoSolitary 

I have allowed Appveyor for the project. You should be able to configure it now.
You can try to reuse https://github.com/dokan-dev/dokan-dotnet/blob/master/appveyor.yml at least for the dokan install part 👍 

This looks very promising! #NotRustDev: Does crates.io is the main resource to store rust library ? Like nuget.org for C# ?

**Comment by DDoSolitary** [comment]
Thanks a lot for your help :)

> Does crates.io is the main resource to store rust library?

Yes, it's the official package registry for Rust

**Comment by DDoSolitary** [comment]
@Liryna Strangely, I'm still unable to find dokan-rust in the New Project page of AppVeyor.

Yesterday I used "Update installations" button on that page to request access and now after clicking that button I can see the dokan-dev organization is shown as configurable, indicating that access has been granted.

![图片](https://user-images.githubusercontent.com/25856103/74397433-9b1d6800-4e4f-11ea-9284-1eda6f01d166.png)

After clicking the configure button, the page says "Selected 1 repository", which is expected, but the list below is empty.

![图片](https://user-images.githubusercontent.com/25856103/74397673-36164200-4e50-11ea-8c1b-a4afa6ecf660.png)

Then I clicked the "Select repositories", and dokan-rust does appears as installed.

![图片](https://user-images.githubusercontent.com/25856103/74397846-99a06f80-4e50-11ea-9483-8e1d8713137f.png)

However, as I said at the beginning, I'm unable to find dokan-dev or dokan-rust in the New Project page.

Did I make any mistakes? Or probably the problem is on AppVeyor or GitHub side and I should contact their customer support?

**Comment by DDoSolitary** [comment]
BTW, maybe I can use GitHub Actions for CI. I've been using it for my personal projects and it works pretty.

**Comment by Liryna** [comment]
Hi @DDoSolitary ,

I had an error when I accepted to add you to appveyor.... so we will try to use Webhooks. It seems to be enabled for pull_req / push and the project will be here https://ci.appveyor.com/project/Liryna/dokan-rust 

Let me know if it really work when you will push 🤞

**Comment by DDoSolitary** [comment]
@Liryna It is working well. Thanks a lot for your help.

**Comment by Liryna** [comment]
Thanks to you to bringing a new compatible language for dokan! 🏆 

When you are ready. I would suggest to add a readme with all the badges and small "how to use"
People like "sample", you can link your own project as sample or create a simple FS like a memory FS using your Rust wrapper 👍 

I already added here https://github.com/dokan-dev/dokany/wiki/Dokan-API-Wrappers-language-compatible

**Comment by DDoSolitary** [comment]
>  People like "sample", you can link your own project as sample or create a simple FS like a memory FS using your Rust wrapper 👍

A memfs example is now available: https://github.com/dokan-dev/dokan-rust/tree/master/dokan/examples/memfs

**Comment by Liryna** [comment]
Congrats @DDoSolitary ! That's an awesome work you did there! memfs is the best example to provide to users :+1:
