### ISSUE TITLE
Notepad is not able to save the file 

### ISSUE THREAD

**Issue by ajaykumargdr** [dokan-dev/dokan-rust#13]
We were testing our dokan-rust implementation of a mirror drive. We were testing writing into a `.txt` file using Notepad. It was working fine without any issues. 
But currently we are facing a issue were Notepad is not able to save the file. If we press `ctrl+s` or use `File>Save` the notepad is opening `Save-as` explorer box. 
![Screenshot (103)](https://github.com/user-attachments/assets/748b34cf-1c45-4bda-b0ea-753aab7a3521)

Even if we select the same file that we are currently trying to write or with a new name, the notepad is throwing error as `The specified path is invalid.`. 
We tried everything was possible such as reinstalling dokan, installing older version of dokan, running the program in another system. But nothing worked. Even we have tried running the `C:\Program Files\Dokan\Dokan Library-2.1.0\sample\mirror\mirror.exe` program but we got the same error in this program also. 
We also tried tracking the program in `process-monitor`. We didn't see any noticeable error in this. Even we are not getting any kind of errors in our program(dokan-rust implementation). 
![Screenshot (98)](https://github.com/user-attachments/assets/23fbed2d-290b-4781-8632-802befd505ba)

If we tried to edit the same `.txt` file using any other application(VsCode or WordPad) it works fine without any issues.

Dokan Version:
Dokan Library 2.1.0.1000 Bundle

Following is my windows system specification:
Edition	Windows 11 Pro
Version	23H2
Installed on	‎5/‎11/‎2024
OS build	22631.4037
Experience	Windows Feature Experience Pack 1000.22700.1027.0

Notepad version:
Windows Notepad 11.2406.9.0

**Comment by Liryna** [comment]
@ajaykumargdr Please see my comment https://github.com/dokan-dev/dokany/issues/1240#issuecomment-2289112337

**Comment by ajaykumargdr** [comment]
@Liryna This fix resolves the error in the mirror implementation. However, we are implementing our drive as a Network Drive. Since the MOUNT_MANAGER mount flag cannot be used when mounting as a network drive, is there any way to fix this issue for network drives?

**Comment by Liryna** [comment]
Indeed network drives have an issue. They seem to be trying to call this but we return a failure.
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-file_remote_protocol_information
It could be the reason for the failure or not but that's a start. I will try to test add it locally to see if it improves.

**Comment by ajaykumargdr** [comment]
@Liryna Thank you for the insight. We also noticed that the issue with Notepad on the network drive is only occurring in the latest version `11.2406.9.0`. We checked the previous version `11.2404.10.0`, and it works fine for us.

**Comment by Liryna** [comment]
Notepad is now sending `IOCTL_MOUNTDEV_QUERY_DEVICE_NAME` which we support but as the comment says, the request might fail if it is compared to the mount manager DB (which we are not using for network drive)
https://github.com/dokan-dev/dokany/blob/7f25947970c1dc23cd3be9a0dbdb41f96e54f513/sys/device.c#L281-L300

**Comment by koimatcha** [comment]
Hi.
This issue seems to be resolved by Notepad version 11.2407.8.0.
