### ISSUE TITLE
Documentation hosting

### ISSUE THREAD

**Issue by DDoSolitary** [dokan-dev/dokan-rust#2]
@Liryna Is it possible to host documentation pages of this project on dokan-dev.github.io, like what has been done for dokany and dokan-dotnet?

Normally documentation of Rust packages are expected to be hosted on docs.rs. However, their build environment doesn't provide Windows SDK, which is required to build this project. So self-hosting seems to be the only option.

**Comment by DDoSolitary** [comment]
It seems that <del>the build environment does have Windows SDK installed and</del> the actual reason is that [cc](https://github.com/alexcrichton/cc-rs) returns the gnu compiler in that environment even when targeting msvc. It needs more investigation.

**Comment by DDoSolitary** [comment]
Well...
Finally I realized that docs.rs runs in a Linux environment and is crossing compiling for the default target I specified (msvc). So there's definitely no way to rely on docs.rs for documentation and self-hosting is still needed.

**Comment by Liryna** [comment]
Hi,

Sorry wanted to already answer yesterday.
I can give you access to the appveyor build the ability to push the
documentation if you would like.
Could you just add all the steps to generate it and point me the output
folder? I will do the last steps for the push.

Le mar. 18 févr. 2020 à 07:28, DDoSolitary <notifications@github.com> a
écrit :

**Comment by DDoSolitary** [comment]
@Liryna The current build script is already building the documentation as well. The output directory is `target\doc`

**Comment by Liryna** [comment]
Perfect! Will try to do it today or during the week. Thank you!

Le mar. 18 févr. 2020 à 09:22, DDoSolitary <notifications@github.com> a
écrit :

**Comment by Liryna** [comment]
Here you go @DDoSolitary https://github.com/dokan-dev/dokan-rust/commit/f44e502e4fabcc53fcabdce83abf6ca9f72fddbe 👍 
https://github.com/dokan-dev/dokan-rust-doc
https://dokan-dev.github.io/dokan-rust-doc/html/dokan/index.html

**Comment by DDoSolitary** [comment]
@Liryna The CI script is no longer able to push to doc repo, it says:

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/dokan-dev/dokan-rust-doc.git/'
```

https://ci.appveyor.com/project/Liryna/dokan-rust/builds/39384459/job/k90gii3ew76wwev3

Could you please take a look?

**Comment by DDoSolitary** [comment]
BTW, I guess deploy keys are a better option than access tokens for this scenario. It provides find-grained access control and only allows access to a specific repo rather than everything under an account.

**Comment by Liryna** [comment]
@DDoSolitary I checked again the user access and everything looks good so I regenerated the access token. 
https://ci.appveyor.com/project/Liryna/dokan-rust/build/job/k2rqvjkau2dwd1wy hasn't tried to upload the new doc, do you have an idea how to force that ?

**Comment by DDoSolitary** [comment]
I changed the script so that documentation is only updated for tags. I just triggered a doc update by updating an existing tag to the new commit. The CI builds are currently queued so we need to wait for some time to see the results.

**Comment by DDoSolitary** [comment]
It's working now: https://ci.appveyor.com/project/Liryna/dokan-rust/builds/39386850/job/esgecv2oyf8ta2x5 🚀 
Thanks!
